# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "04f7b5739bab88b99a4819120a6ac275"
name = "discount"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_gift_cards,write_gift_cards,read_discounts,write_discounts"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[app_proxy]
url = "https://example.com/api/proxy"
subpath = "gift-card-check"
prefix = "apps"

[build]
automatically_update_urls_on_dev = true
